# Generated by Django 5.2.6 on 2026-01-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('company_name', models.CharField(max_length=200)),
                ('upperLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lowerLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alertEnabled', models.BooleanField(default=False)),
                ('upperAlertTriggered', models.BooleanField(default=False)),
                ('lowerAlertTriggered', models.BooleanField(default=False)),
                ('last_alert_type', models.CharField(blank=True, max_length=20, null=True)),
                ('alertTriggerTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
