# Generated by Django 5.2.6 on 2026-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedstock',
            name='latestPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trackedstock',
            name='marketClosed',
            field=models.BooleanField(default=False),
        ),
    ]
