# Generated by Django 4.2.27 on 2026-06-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_trackedstock_latestprice_trackedstock_marketclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedstock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
